version: "3"
services:
  natter-nginx-cf:
    command: -e /opt/cf-redir.py -p 18888
    volumes:
      - ./cf-redir.py:/opt/cf-redir.py
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    image: nattertool/natter
    restart: always
    depends_on:
      - nginx

  nginx:
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "18888:80"
    environment:
      - TZ=Asia/Shanghai
    image: nginx
    restart: always

  natter-v2fly:
    command: -e /opt/v2subsc.py -p 19999
    volumes:
      - ./v2subsc.py:/opt/v2subsc.py
      - ./html:/usr/share/nginx/html
      - ./config.json:/etc/v2ray/config.json
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    image: nattertool/natter
    restart: always
    depends_on:
      - v2fly

  v2fly:
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./config.json:/etc/v2ray/config.json
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    image: v2fly/v2fly-core
    restart: always
